### ISSUE TITLE
Error		The "GenerateResourceDesigner" task failed unexpectedly.

### ISSUE THREAD

**Issue by john1726** [xamarin/xamarin-forms-book-samples#7]
Presently, I am attempting to build this solution using Visual Studio 2015 Version 14.0.25123.00 Update 2 and Windows 10 Version 1511 build 10586.420:

`~\xamarin-forms-book-samples-master\Chapter18\MvvmClock\MvvmClock.sln`

This is one of the errors I'm getting:

```
Severity    Code    Description Project File    Line    Suppression State
Error       The "GenerateResourceDesigner" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'MvvmClock, Version=, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'MvvmClock.dll'
   at Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve(String fullName, ReaderParameters parameters)
   at Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve(String fullName)
   at Xamarin.Android.Tuner.DirectoryAssemblyResolver.GetAssembly(String fileName)
   at Xamarin.Android.Tasks.GenerateResourceDesigner.<Execute>c__AnonStorey0.<>m__0(String ass)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at Xamarin.Android.Tasks.ResourceDesignerImportGenerator.CreateImportMethods(IEnumerable`1 libraries)
   at Xamarin.Android.Tasks.GenerateResourceDesigner.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() MvvmClock.Droid C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets   1225    
```

Does anyone have any suggestions?  TIA.

**UPDATE:**

Also getting this error:

```
Severity    Code    Description Project File    Line    Suppression State
Error       The "GetAdditionalResourcesFromAssemblies" task failed unexpectedly.
System.UnauthorizedAccessException: Access to the path '~\xamarin-forms-book-samples-master\Chapter18\MvvmClock\MvvmClock\MvvmClock.Droid\obj\Debug\resourcepaths.cache' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)
   at System.Xml.XmlWriter.Create(String outputFileName, XmlWriterSettings settings)
   at System.Xml.Linq.XDocument.Save(String fileName, SaveOptions options)
   at System.Xml.Linq.XDocument.Save(String fileName)
   at Xamarin.Android.Tasks.GetAdditionalResourcesFromAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() MvvmClock.Droid C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets   348 
```

**Comment by sreeeravankara** [comment]
Hi John, Try opening the Libraries\Xamarin.FormsBook.Toolkit Project separately and restore NuGet. Also update Xamarin  for Libraries\Xamarin.FormsBook.Toolkit Project. This solved my issue.
